### PR TITLE
Improve performace in looking up an address in the address.txt file

### PR DESCRIPTION
**Pull request by minhhieugma**
The original code will face a problem in finding an address in a big list. I did try the code with an address.txt file with a few million records. It is extremely slow (less than 100 addresses/s). 

Solution: use the dictionary to speed up this task (12,000 addresses/s)

### CODE REVIEW

**Comment by minhhieugma** [comment]
Can we bypass the CodeFactor issue here?

**Comment by SubGlitch1** [comment]
i guess we could use sqlite3?

**Comment by minhhieugma** [comment]
@vlnahp hi, what do you think about this PR?

**Review by vlnahp — COMMENTED** [review]
Have you tested it? 
It seems not to work.

**Review by vlnahp — CHANGES_REQUESTED** [review]
Change `lines_data` to `load_data` in lines 46 and 60.

**Review by vlnahp — APPROVED** [review]

**Pull request merged**
