### PR TITLE
added logo

### PR DESCRIPTION
**Pull request by SubGlitch1**
it looks weird in the file but pretty nice when you run it in any terminal really.
Just an idea tbh i think it adds some character to the repo if that makes sense lol

### CODE REVIEW

**Review by vlnahp — COMMENTED** [review]
It's just too big! I think it will be annoying to the clients.

**Comment by getbread3015** [comment]
> It's just too big! I think it will be annoying to the clients.

hi , im having issues with the program may i get some assistance please

**Comment by marssystems** [comment]
> > It's just too big! I think it will be annoying to the clients.
> 
> hi , im having issues with the program may i get some assistance please

What issues are you having with the program?

**Comment by getbread3015** [comment]
> > > It's just too big! I think it will be annoying to the clients.
> > 
> > 
> > hi , im having issues with the program may i get some assistance please
> 
> What issues are you having with the program?

honestly i just dont know how to use it, do you have telegram so i can contact you

**Comment by getbread3015** [comment]
i bought from someone and i dont know how to use the software

**Comment by marssystems** [comment]
No - I don't have telegram - but the instructions are very simple

Quick Start
 $ git clone https://github.com/vlnahp/Btcbf.git

 $ cd Btcbf

 $ pip install -r requirements.txt

 $ python Btcbf.py or  $ python3 Btcbf.py on Linux

Which part is giving you problems?

**Comment by marssystems** [comment]
Is your computer a Windows or Linux machine?

**Comment by getbread3015** [comment]
its windows and i have the program up 
i just dont know how to use it to generate wallets and private key

**Comment by marssystems** [comment]
You don't need to generate any wallets or private keys. Just start the program and follow the instructions.

**Comment by marssystems** [comment]
Have you got python installed on your PC?

**Comment by getbread3015** [comment]
then i may need help downloading this program here in github i bought the program from someone he was suppose to guide me but disappeared

**Comment by getbread3015** [comment]
can i send share of my screen here

**Comment by getbread3015** [comment]
yes python downloaded

**Comment by marssystems** [comment]
Do you have the program in a folder on your Windows PC?

**Comment by getbread3015** [comment]
yes

**Comment by getbread3015** [comment]
let me share the screen to make sure its the correct program i might of been hustled

**Comment by marssystems** [comment]
OK - go to the folder and create a .bat file inside that folder. Call it btcbf.bat

Edit the file in notepad and insert -

python Btcbf.py

into it and save it.

then just double click the btcbf.bat file to run it.

**Comment by getbread3015** [comment]
Untitled

**Comment by getbread3015** [comment]
> OK - go to the folder and create a .bat file inside that folder. Call it btcbf.bat
> 
> Edit the file in notepad and insert -
> 
> python Btcbf.py
> 
> into it and save it.
> 
> then just double click the btcbf.bat file to run it.

okay

**Comment by marssystems** [comment]
No - this is not the program.

**Comment by marssystems** [comment]
This program is called btcbf.py

**Comment by getbread3015** [comment]
image

**Comment by getbread3015** [comment]
all of the files that are in btcbf are in this folder with this  program

**Comment by getbread3015** [comment]
okay how do i download the real program

**Comment by getbread3015** [comment]
from the start would like help to install btcbf

**Comment by marssystems** [comment]
These are  the files that you should have in your folder -

Btcbf.py
LICENSE
README.md
_config.yml
address.txt
requirements.txt

You can download them from the "Code" section.

**Comment by getbread3015** [comment]
ok i have downloaded the main file what do i do now

**Comment by getbread3015** [comment]
btcbf file wont open

**Comment by marssystems** [comment]
Put  btcbf,py and address.txt in your btcbf folder.

Then create the .bat file and run it.

**Comment by marssystems** [comment]
Make sure you have installed the requirements.txt file in Python first.

**Comment by marssystems** [comment]
Follow the instructions here -

https://github.com/vlnahp/Btcbf

**Comment by getbread3015** [comment]
image

**Comment by getbread3015** [comment]
like this ?

**Comment by getbread3015** [comment]
Make sure you have installed the requirements.txt file in Python first.
just copy and paste to python ?

**Comment by marssystems** [comment]
Yes - looks good.

**Comment by getbread3015** [comment]
i dont know how to use python to add those 
can u guide me pplease

**Comment by marssystems** [comment]
No - you needto open a CMD window and run -

pip install -r requirements.txt

You will need to navigate to your btcbf folder first.

**Comment by getbread3015** [comment]
ok doing now

**Comment by getbread3015** [comment]
im in the cmd
 whats the first thing i put in there ? pip install -r requirements.txt?

**Comment by marssystems** [comment]
No - cd to your btcbf dir first. Then input the command.

**Comment by getbread3015** [comment]
image

**Comment by getbread3015** [comment]
like this

**Comment by marssystems** [comment]
Yes - now input the command

**Comment by getbread3015** [comment]
image

**Comment by marssystems** [comment]
Do a dir to make sure you are in the right directory

I think it should be C:/Users/Owner/Downloads/Btcbf-main/Btcbf-main

**Comment by getbread3015** [comment]
image

**Comment by getbread3015** [comment]
check it out

**Comment by marssystems** [comment]
Yep! - that;s got it!

Now you can run the bat file.

**Comment by getbread3015** [comment]
the bat file is just a txt was i suppose to add something in there

**Comment by getbread3015** [comment]
image

**Comment by marssystems** [comment]
Edit the file in notepad and insert -

python Btcbf.py

into it and save it.

then just double click the btcbf.bat file to run it.

**Comment by getbread3015** [comment]
image

**Comment by getbread3015** [comment]
image

**Comment by marssystems** [comment]
Yes - that is correct. now save it and run it.

**Comment by getbread3015** [comment]
save and run btcbf in python ?

**Comment by marssystems** [comment]
No - just double click the btcbf.bat file.

**Comment by getbread3015** [comment]
i did it just opens text

**Comment by marssystems** [comment]
OK - rename the btcbf.bat file to btcbf.cmd

**Comment by getbread3015** [comment]
same

image

**Comment by marssystems** [comment]
Does it run now?

**Comment by getbread3015** [comment]
no it just opens the textt

**Comment by getbread3015** [comment]
when i click the python file it opens this

**Comment by getbread3015** [comment]
image

**Comment by marssystems** [comment]
Strange - something isn't set in Windows 11 to make it run.

Right click the file and look at the properties.

**Comment by getbread3015** [comment]
the python file ?

**Comment by getbread3015** [comment]
do you have an icq or whatsapp

**Comment by marssystems** [comment]
Yes - look at the properties of the btcbf.cmd file.

Try - right click and select - run as administrator - to see what happens.

**Comment by getbread3015** [comment]
there is no run as administator its in txt.file

**Comment by marssystems** [comment]
If you right-click the btcbf.cmd file - the 'Run as Administrator' option is the second one down in the pop-up menu.

**Comment by getbread3015** [comment]
yeah its not there for me

**Comment by getbread3015** [comment]
the btcbf.cmd is in txt file let me show u

**Comment by getbread3015** [comment]
image

**Comment by getbread3015** [comment]
image

**Comment by marssystems** [comment]
OK - rename it back to .bat and its description should change from Text Document to Windows Batch File.

**Comment by getbread3015** [comment]
got it

**Comment by getbread3015** [comment]
image

**Comment by marssystems** [comment]
That's great! - We go there in the end!

**Comment by getbread3015** [comment]
how to i generate wallets with private keys

**Comment by getbread3015** [comment]
in bulk

**Comment by getbread3015** [comment]
3 or 4

**Comment by getbread3015** [comment]
and where do i see results

**Comment by marssystems** [comment]
I don't  know. I use option 3 then option 1 then 4 cores.

**Comment by getbread3015** [comment]
and that gives you ?

**Comment by getbread3015** [comment]
where do you see your results

**Comment by marssystems** [comment]
Just try all the options one by one and see what they do.

**Comment by marssystems** [comment]
The results appear in the CMD window - try it!

**Comment by getbread3015** [comment]
i did that  i see what they do

**Comment by getbread3015** [comment]
i just dont know when it finishes and where to see the results of wallets and private key

**Comment by getbread3015** [comment]
> The results appear in the CMD window - try it!

how do i check that lol im sorry

**Comment by marssystems** [comment]
The results will appear in the program window.

**Comment by getbread3015** [comment]
in the same cmd program thats its bruting in ?

**Comment by getbread3015** [comment]
what elpased time does it usually finish or start showing results ?

**Comment by getbread3015** [comment]
i did 3 1 4

**Comment by marssystems** [comment]
As its random - your guess is as good as mine - could take a while.

**Comment by getbread3015** [comment]
how often you use this

**Comment by getbread3015** [comment]
and do you use it to generate wallet and private key

**Comment by getbread3015** [comment]
also thank u

**Comment by marssystems** [comment]
I run it all the time to find the private keys of bitcoin addresses in the address.txt file.

I don't generate wallets or private keys - no need for them.

**Comment by marssystems** [comment]
Your're welcome!

**Comment by getbread3015** [comment]
i seee so you get wallets and find the private key viaaa 3 1 4 okay i got it

**Comment by marssystems** [comment]
Yes

**Comment by getbread3015** [comment]
thank you man such help

**Comment by marssystems** [comment]
Enjoy!

**Comment by vlnahp** [comment]
What have you been doing here?!
It's not the place to fix your issues. It has its dedicated page.

**Pull request closed without merging**
